# app/config/parameters.yml
parameters:
    database_driver:    pdo_pgsql
    database_host:      localhost
    database_name:      postgres
    database_user:      postgres
    database_password:  ""

# ...
